{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "base-workload.name" . }}-secret
  labels:
    {{- include "base-workload.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $key,$val := .Values.secrets }}
  {{ $key }}: {{$val | quote }}
{{- end }}
{{- end }}