apiVersion: v1
kind: Service
metadata:
  name: {{ include "base-workload.name" . }}
  labels:
    {{- include "base-workload.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- toYaml .Values.service.ports | nindent 4 }}
  selector:
    {{- include "base-workload.selectorLabels" . | nindent 4 }}
